# Generated by Django 4.0 on 2022-01-20 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ManyToManyField(related_name='listings', to='auctions.category'),
        ),
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.ManyToManyField(related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ManyToManyField(related_name='bids', to='auctions.listings')),
                ('user', models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
