# Generated by Django 4.0 on 2022-01-21 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listings_category_listings_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ManyToManyField(related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ManyToManyField(related_name='cat_listings', to='auctions.category'),
        ),
    ]
