# Generated by Django 4.0 on 2022-01-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bids_user_bids_user_remove_listings_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to='auctions.user'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(default='CLOTHES', on_delete=django.db.models.deletion.CASCADE, related_name='cat_listings', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.user'),
        ),
    ]
