# Generated by Django 4.0 on 2022-01-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bids_listing_bids_listing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
