# Generated by Django 4.0 on 2022-01-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category_alter_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='watching', to='auctions.listing')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.user')),
            ],
        ),
    ]
