# Generated by Django 4.0 on 2022-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BID', 'Bidding'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
